openapi: 3.0.0
info:
  title: Fixed Deposit API
  description: Fixed Deposit API
  version: 1.0.0

servers:
  - url: http://localhost:4010

paths:
  /api/v1/fixed-deposits:
    get:
      summary: fixed-deposits
      operationId: get-fixed-deposit
      responses:
        '200':
          description: 'Successful'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FixedDepositResponse'

components:
  schemas:
    FixedDepositResponse:
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
        name:
          type: string
          x-faker: name.firstName
        account:
          type: string
        amount:
          type: number
          format: decimal
