openapi: 3.0.0
info:
  title: Fixed Deposit API
  description: Fixed Deposit API
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'

paths:
  /api/v1/fixed-deposit:
    get:
      summary: get-fixed-deposit
      operationId: get-fixed-deposit
      responses:
        200:
          $ref: '#/components/schemas/FixedDepositResponse'

components:
  schemas:
    FixedDepositResponse:
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        account:
          type: string
        amount:
          type: number
          format: decimal
