version: '3'
services:
  mock-api:
    image: stoplight/prism:4
    command: 'mock -h 0.0.0.0 /tmp/api.yml -d'
    volumes:
      - ./docs/specs/api-contract.yaml:/tmp/api.yml:ro
    ports:
      - '4010:4010'